### ISSUE TITLE
Ubuntu 21.10 Segmentation Fault on clean install of 0.20.17 pocketcoin-qt

### ISSUE THREAD

**Issue by Dylan-86** [pocketnetteam/pocketnet.core#170] opened 2022-01-19 15:27 UTC
Hi,
I've successfully installed the pocketnet.core deb.

I've downloaded manually the checkpoints db and put in in /home/.pocketcoin/checkpoints

Open terminal
`pocketcoin-qt`

```
0000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
0000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
Segmentation fault (core dumped)
```

Open Log
2022-01-19T15:25:38Z Pocketnet Core version v0.20.17 (release build)
2022-01-19T15:25:38Z InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2022-01-19T15:25:38Z Assuming ancestors of block 61276732ac5226282d46937b3a4609ed06e98f6621a68941c649ac507dd143bc have valid signatures.
2022-01-19T15:25:38Z Setting nMinimumChainWork=00000000000000000000000000000000000000000000002e9b7b6eb4a23574f0
2022-01-19T15:25:38Z Using the 'shani(1way,2way)' SHA256 implementation
2022-01-19T15:25:38Z Using RdRand as an additional entropy source
2022-01-19T15:25:38Z Default data directory /home/ddy/.pocketcoin
2022-01-19T15:25:38Z Using data directory /home/ddy/.pocketcoin
2022-01-19T15:25:38Z Config file: /home/ddy/.pocketcoin/pocketcoin.conf (not found, skipping)
2022-01-19T15:25:38Z Using at most 125 automatic connections (1024 file descriptors available)
2022-01-19T15:25:38Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
2022-01-19T15:25:38Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
2022-01-19T15:25:38Z Using 8 threads for script verification
2022-01-19T15:25:38Z init message: Loading Pocket DB...
2022-01-19T15:25:38Z scheduler thread start
2022-01-19T15:25:38Z SQLite usage version: 3037000
2022-01-19T15:25:38Z ErrorLogCallback: 283; Message: recovered 302 frames from WAL file /home/ddy/.pocketcoin/pocketdb/main.sqlite3-wal
2022-01-19T15:25:38Z Creating Sqlite database `main.sqlite3` structure..
2022-01-19T15:25:38Z Creating Sqlite database `web.sqlite3` structure..
2022-01-19T15:25:38Z Using wallet directory /home/ddy/.pocketcoin/wallets
2022-01-19T15:25:38Z init message: Verifying wallet(s)...
2022-01-19T15:25:38Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2022-01-19T15:25:38Z Using wallet wallet.dat
2022-01-19T15:25:38Z BerkeleyEnvironment::Open: LogDir=/home/ddy/.pocketcoin/wallets/database ErrorFile=/home/ddy/.pocketcoin/wallets/db.log
2022-01-19T15:25:38Z Cache configuration:
2022-01-19T15:25:38Z * Using 2.0MiB for block index database
2022-01-19T15:25:38Z * Using 8.0MiB for chain state database
2022-01-19T15:25:38Z * Using 160.0MiB for in-memory UTXO set (plus up to 286.1MiB of unused mempool space)
2022-01-19T15:25:38Z init message: Loading block index...
2022-01-19T15:25:38Z Opening LevelDB in /home/ddy/.pocketcoin/blocks/index
2022-01-19T15:25:38Z Opened LevelDB successfully
2022-01-19T15:25:38Z Using obfuscation key for /home/ddy/.pocketcoin/blocks/index: 0000000000000000
2022-01-19T15:25:38Z LoadBlockIndexDB: last block file = 0
2022-01-19T15:25:38Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=0, size=0, heights=0...0, time=1970-01-01...1970-01-01)
2022-01-19T15:25:38Z Checking all blk files are present...
2022-01-19T15:25:38Z Initializing databases...
2022-01-19T15:25:38Z Opening LevelDB in /home/ddy/.pocketcoin/chainstate
2022-01-19T15:25:38Z Opened LevelDB successfully
2022-01-19T15:25:38Z Using obfuscation key for /home/ddy/.pocketcoin/chainstate: 8076e700f0e92c4a
2022-01-19T15:25:38Z init message: Rewinding blocks...
2022-01-19T15:25:38Z  block index              14ms
2022-01-19T15:25:38Z Opening LevelDB in /home/ddy/.pocketcoin/indexes/txindex
2022-01-19T15:25:38Z Opened LevelDB successfully
2022-01-19T15:25:38Z Using obfuscation key for /home/ddy/.pocketcoin/indexes/txindex: 0000000000000000
2022-01-19T15:25:38Z init message: Loading wallet...
2022-01-19T15:25:38Z txindex thread start
2022-01-19T15:25:38Z txindex is enabled
2022-01-19T15:25:38Z txindex thread exit
2022-01-19T15:25:38Z Failed to open mempool file from disk. Continuing anyway.
2022-01-19T15:25:38Z mapBlockIndex.size() = 1
2022-01-19T15:25:38Z Best block: 00000fd0f6633d395541056e8adc32961e15f8133674b2e3937c4d210ced6f3f (0)
2022-01-19T15:25:38Z Staker thread started for 
2022-01-19T15:25:38Z Bound to [::]:37070
2022-01-19T15:25:38Z Bound to 0.0.0.0:37070
2022-01-19T15:25:38Z init message: Loading P2P addresses...
2022-01-19T15:25:38Z torcontrol thread start
2022-01-19T15:25:38Z Loaded 0 addresses from peers.dat  1ms
2022-01-19T15:25:38Z init message: Loading banlist...
2022-01-19T15:25:38Z init message: Starting network threads...
2022-01-19T15:25:38Z net thread start
2022-01-19T15:25:38Z dnsseed thread start
2022-01-19T15:25:38Z Loading addresses from DNS seeds (could take a while)
2022-01-19T15:25:38Z addcon thread start
2022-01-19T15:25:38Z 0 addresses found from DNS seeds
2022-01-19T15:25:38Z dnsseed thread exit
2022-01-19T15:25:38Z msghand thread start
2022-01-19T15:25:38Z opencon thread start
2022-01-19T15:25:38Z init message: Done loading
2022-01-19T15:25:38Z GUI: Platform customization: "other"
2022-01-19T15:25:38Z GUI: PaymentServer::LoadRootCAs: Loaded  125  root certificates

Any idea?
Then, how do I configure everything, including my wallet addres?!

The instructions in the readme.MD are not clear at all...

**Comment by andyoknen** [comment] 2022-01-19 16:56
Maybe try to run in debugging using GDB ? This may give more information about the problem
```
$ sudo apt install gdb
$ gdb pocketcoind
```

**Comment by Dylan-86** [comment] 2022-01-19 17:06
Not that useful:

ddy@ddy--50909:~$ gdb pocketcoind

GNU gdb (Ubuntu 11.1-0ubuntu2) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from pocketcoind...
(No debugging symbols found in pocketcoind)
(gdb) 



Am I missing something?

**Comment by andyoknen** [comment] 2022-01-20 05:07
Everything is fine, you need to enter "r" to run

**Comment by tawmaz** [comment] 2022-01-20 17:12
From the terminal output it is crashing with a segmentation fault.  What Ubuntu version are you running?  What is your system hardware configuration?

**Comment by Dylan-86** [comment] 2022-01-20 17:19
> From the terminal output it is crashing with a segmentation fault. What Ubuntu version are you running? What is your system hardware configuration?

Ubuntu 21.10
CPU i5-1135g7
16 gb ram
250 GB SSD

**Comment by tawmaz** [comment] 2022-01-27 04:20
I have a repro on this segmentation fault when performing a clean install and attempting to run pocketcoin-qt on Ubuntu 21.10.  If possible it would be good for us to get a fix into 20.18.

**Comment by andyoknen** [comment] 2022-01-27 16:21
> I have a repro on this segmentation fault when performing a clean install and attempting to run pocketcoin-qt on Ubuntu 21.10. If possible it would be good for us to get a fix into 20.18.

@tawmaz Do you have a solution?

**Comment by tawmaz** [comment] 2022-01-27 17:33
I will investigate some more today.  The segmentation fault does not show a stack, and appears to be crashing inside the QT library.  As a workaround it is possible to run pocketcoind, but the GUI does not appear to work on Ubuntu 21.10.

There are two messages printed to the console before crashing:
"Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome.  Use QT_QPA_PLATFORM=wayland to run on Wayland anyway."
"Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created."

**Comment by andyoknen** [comment] 2022-01-27 18:32
I think it can no longer be released in 0.20.18 and is not urgent enough. In any case, we plan to abandon the bitcoin GUI in the future, replacing it with a web interface.

**Comment by tawmaz** [comment] 2022-01-27 21:39
I am running into a some issues with Ubuntu 21.10 requiring me to re-install.  I would suggest we recommend Ubuntu 20.04 in the setup guide.

**Comment by tawmaz** [comment] 2022-01-30 06:04
Fix: https://github.com/pocketnetteam/pocketnet.core/pull/176

**Comment by tawmaz** [comment] 2022-02-03 18:49
@Dylan-86 please try with 0.20.18 as it has a segmentation fault fix with pocketcoin-qt.  Feel free to re-open this issue if the problem is still present.

**Closed as completed by tawmaz** 2022-02-03 18:49 UTC
