### ISSUE TITLE
Running pocketcoind, looks to stuck, repeating the same over and over

### ISSUE THREAD

**Issue by pmathieu73** [pocketnetteam/pocketnet.core#7] opened 2021-03-09 19:17 UTC
Should this be happening?
This is what shows on my screen:

2021-03-09T19:05:20Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:05:24Z New outbound peer connected: version: 70015, blocks=1081968, peer=41
2021-03-09T19:05:25Z ERROR: AcceptBlockHeader: block 67abd15550bd2c8257c1649b310bb7394f35c56334d11491ab928f131f8b5e99 is marked invalid
2021-03-09T19:05:36Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:05:44Z New outbound peer connected: version: 70015, blocks=1076824, peer=42
2021-03-09T19:05:44Z ERROR: AcceptBlockHeader: block 67abd15550bd2c8257c1649b310bb7394f35c56334d11491ab928f131f8b5e99 is marked invalid
2021-03-09T19:05:46Z New outbound peer connected: version: 70015, blocks=1081969, peer=43
2021-03-09T19:05:52Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:05:55Z New outbound peer connected: version: 70015, blocks=1081969, peer=44
2021-03-09T19:05:55Z ERROR: AcceptBlockHeader: block 67abd15550bd2c8257c1649b310bb7394f35c56334d11491ab928f131f8b5e99 is marked invalid
2021-03-09T19:05:58Z New outbound peer connected: version: 70015, blocks=1081969, peer=45
2021-03-09T19:05:59Z ERROR: AcceptBlockHeader: block 67abd15550bd2c8257c1649b310bb7394f35c56334d11491ab928f131f8b5e99 is marked invalid
2021-03-09T19:06:08Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:06:24Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:06:40Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:06:56Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:07:12Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:07:28Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:07:44Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:08:00Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:08:16Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:08:32Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:08:39Z Potential stale tip detected, will try using extra outbound peer (last tip update: 3780 seconds ago)
2021-03-09T19:08:48Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:09:04Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:09:20Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:09:36Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:09:52Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:10:08Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:10:24Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:10:40Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:10:56Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:11:12Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:11:28Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:11:44Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:12:00Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:12:16Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:12:32Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:12:48Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:13:04Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:13:20Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:13:36Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:13:52Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:14:08Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:14:24Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:14:40Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:14:56Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:15:12Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:15:28Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:15:34Z New outbound peer connected: version: 70015, blocks=1081977, peer=48
2021-03-09T19:15:35Z ERROR: AcceptBlockHeader: block 67abd15550bd2c8257c1649b310bb7394f35c56334d11491ab928f131f8b5e99 is marked invalid
2021-03-09T19:15:44Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6
2021-03-09T19:15:49Z New outbound peer connected: version: 70015, blocks=1076824, peer=49
2021-03-09T19:15:50Z ERROR: AcceptBlockHeader: block 67abd15550bd2c8257c1649b310bb7394f35c56334d11491ab928f131f8b5e99 is marked invalid
2021-03-09T19:15:56Z New outbound peer connected: version: 70015, blocks=1081977, peer=50
2021-03-09T19:15:57Z ERROR: AcceptBlockHeader: block 67abd15550bd2c8257c1649b310bb7394f35c56334d11491ab928f131f8b5e99 is marked invalid
2021-03-09T19:16:00Z Available coins count 0 BestHeader: 100111 11332b98b5ce1929f776852fe423ea861a6da114721d97e7de41fbaf937b54e6

**Comment by andyoknen** [comment] 2021-03-15 13:33
Duplicate of #6 
What is the version of your software? Does the reconsiderblock command help you?

**Comment by pmathieu73** [comment] 2021-03-15 15:45
v0.19.2
pocketcoin-cli reconsiderblock "67abd15550bd2c8257c1649b310bb7394f35c56334d11491ab928f131f8b5e99"
This is what it looks like after reconsiderblock:
2021-03-15T15:36:48Z Available coins count 0 BestHeader: 100928 7977b281f4181265228b9a57ac2c31fe66ee8e689b063589ea38b31e83bbb976
2021-03-15T15:37:04Z Available coins count 0 BestHeader: 100928 7977b281f4181265228b9a57ac2c31fe66ee8e689b063589ea38b31e83bbb976
2021-03-15T15:37:20Z Available coins count 0 BestHeader: 100928 7977b281f4181265228b9a57ac2c31fe66ee8e689b063589ea38b31e83bbb976
2021-03-15T15:37:36Z Available coins count 0 BestHeader: 100928 7977b281f4181265228b9a57ac2c31fe66ee8e689b063589ea38b31e83bbb976
2021-03-15T15:37:52Z Available coins count 0 BestHeader: 100928 7977b281f4181265228b9a57ac2c31fe66ee8e689b063589ea38b31e83bbb976
2021-03-15T15:37:56Z New outbound peer connected: version: 70015, blocks=1090345, peer=13422
2021-03-15T15:38:08Z Available coins count 0 BestHeader: 100928 7977b281f4181265228b9a57ac2c31fe66ee8e689b063589ea38b31e83bbb976
2021-03-15T15:38:24Z Available coins count 0 BestHeader: 100928 7977b281f4181265228b9a57ac2c31fe66ee8e689b063589ea38b31e83bbb976
2021-03-15T15:38:40Z Available coins count 0 BestHeader: 100928 7977b281f4181265228b9a57ac2c31fe66ee8e689b063589ea38b31e83bbb976
2021-03-15T15:38:52Z New outbound peer connected: version: 70015, blocks=1090349, peer=13423
2021-03-15T15:38:53Z New outbound peer connected: version: 70015, blocks=1090349, peer=13424
2021-03-15T15:38:56Z Available coins count 0 BestHeader: 100928 7977b281f4181265228b9a57ac2c31fe66ee8e689b063589ea38b31e83bbb976
2021-03-15T15:39:12Z Available coins count 0 BestHeader: 100928 7977b281f4181265228b9a57ac2c31fe66ee8e689b063589ea38b31e83bbb976
2021-03-15T15:39:28Z Available coins count 0 BestHeader: 100928 7977b281f4181265228b9a57ac2c31fe66ee8e689b063589ea38b31e83bbb976
2021-03-15T15:39:37Z Timeout downloading block aaee9a543674ec080823b4ec93c4d64b5b3e19c46cddd21a9becb9ee3b0d3a20 from peer=13374, disconnecting
2021-03-15T15:39:38Z New outbound peer connected: version: 70015, blocks=1076824, peer=13425
2021-03-15T15:39:38Z New outbound peer connected: version: 70015, blocks=1090349, peer=13426
2021-03-15T15:39:44Z Available coins count 0 BestHeader: 101212 39666f6fef9bdc4d3d646134a452167a17a73c8b8364aee21cb16066b56192db
2021-03-15T15:40:00Z Available coins count 0 BestHeader: 101309 d10e5de942347ab23fcf59ae69808fc39d18267ab17a069d1655d64511e2a956
2021-03-15T15:40:16Z Available coins count 0 BestHeader: 101309 d10e5de942347ab23fcf59ae69808fc39d18267ab17a069d1655d64511e2a956
2021-03-15T15:40:32Z Available coins count 0 BestHeader: 101326 de4bc16e7bf84318b116edd198bc4260a2288b52ddf329f7cfda32408df437f5
2021-03-15T15:40:48Z Available coins count 0 BestHeader: 101459 6ff0cd3d16df9a658844c867ea81fecee9e6a48837b4f4983e479c7254fab2ae
2021-03-15T15:41:04Z Available coins count 0 BestHeader: 101459 6ff0cd3d16df9a658844c867ea81fecee9e6a48837b4f4983e479c7254fab2ae
2021-03-15T15:41:20Z Available coins count 0 BestHeader: 101487 d7a298bf753f823cac28d60210f1fea1903806bf350602beb0ed750c9a3966f5
2021-03-15T15:41:27Z Pre-allocating up to position 0xb00000 in rev00000.dat
2021-03-15T15:41:31Z ANTIBOTRESULT::ReferrerAfterRegistration block ecab2e58de222ed4d26bbce7e5f8934d8da2e3b57c82646b30a6f67986d5c48dAvailable coins count 0 BestHeader: 102622 e86135836dfc26f172d441a9b5cb6cd51ec77241b98fea2612db942e33e6b9c5
2021-03-15T15:41:42Z ANTIBOTRESULT::ReferrerAfterRegistration block d49bb647a9a592cfbfc949cbad21408126ee4c298ffab3c9cbf90146c0502e06Available coins count 0 BestHeader: 103764 2dc6ea11e18de2ba93518d6c754cfe14ef397db31555ca1c92f425e63c87191a
2021-03-15T15:42:08Z Available coins count 0 BestHeader: 103991 1a6ceca1fbb1e73d2a02252cbd4a96741fe493a4b12f25494222b509af15765c
2021-03-15T15:42:24Z Available coins count 0 BestHeader: 104433 a10ffb5eb42e26c5817df6dce588d736d4133e1951616b58647392e16756dc50
2021-03-15T15:42:40Z Available coins count 0 BestHeader: 106273 916fd7117c250e6f7a8a28e2ef1724bf8dc6d35347cccc45b15e7a1f784d9fd7
2021-03-15T15:42:44Z ANTIBOTRESULT::ReferrerAfterRegistration block 73e9665ccae37cf5518295b36bf5017ab22ebedf6372ea1a3247d475f3d68392Available coins count 0 BestHeader: 107845 d21407eaf824d64fc7a8af88887b4c489de0d1b608b83df3d031a0beb2cbe528
2021-03-15T15:43:12Z Available coins count 0 BestHeader: 107845 d21407eaf824d64fc7a8af88887b4c489de0d1b608b83df3d031a0beb2cbe528
2021-03-15T15:43:28Z Available coins count 0 BestHeader: 107845 d21407eaf824d64fc7a8af88887b4c489de0d1b608b83df3d031a0beb2cbe528
2021-03-15T15:43:44Z Available coins count 0 BestHeader: 107845 d21407eaf824d64fc7a8af88887b4c489de0d1b608b83df3d031a0beb2cbe528
2021-03-15T15:44:00Z Available coins count 0 BestHeader: 107845 d21407eaf824d64fc7a8af88887b4c489de0d1b608b83df3d031a0beb2cbe528

Thank you,
Paul

**Closed** 2021-03-15 17:15 UTC
