### ISSUE TITLE
pocketcoin-http segault. Nothing in debug.log

### ISSUE THREAD

**Issue by dmaltsiniotis** [pocketnetteam/pocketnet.core#74] opened 2021-10-27 18:38 UTC
Hello,

Firstly, thank you for the .17 release and addressing the serialization bug, it's a big step forward.

I think there still may be a bug around the transaction rollback process though. Myself and a number of other node operators have noticed that sometimes the pocketcoind process crashes/segaults with no error message in the debug.log file. This seems to happen kind of "randomly" and after a period of a day or two. The debug.log file does not indicate anything went wrong in particular, but the syslog (on Linux) indicates that the process hard-crashed with a segfault, which I've included below.

debug.log last few entries
```
2021-10-27T17:24:32Z Available coins count 5 BestHeader: 1413734 f97a2372105ffe7aa4564371cf384e7d733a662ab2c339042630f45b30f49ef3
2021-10-27T17:24:38Z RIDB rollback to block height 1413733 success!
2021-10-27T17:24:57Z +++ Block connected to chain: 1413734 BH: a8dd2a3aa27417889270b5477e5e9032f125e7772c29dafe8e2413039ecd47d8 CC: 0 (0)
2021-10-27T17:24:57Z +++ Block connected to chain: 1413735 BH: f0d774947e6b9b6c3b3b415b39f711f93b90c7c70fade5acd49e3525bbb26718 CC: 0 (0)
2021-10-27T17:24:57Z Available coins count 5 BestHeader: 1413735 f0d774947e6b9b6c3b3b415b39f711f93b90c7c70fade5acd49e3525bbb26718
2021-10-27T17:25:02Z +++ Block connected to chain: 1413736 BH: 05b471d200fc1a2e101292cea31def2f5dc6ace81005d7d38ef666789e916a57 CC: 1 (104457)
2021-10-27T17:25:04Z Available coins count 5 BestHeader: 1413736 05b471d200fc1a2e101292cea31def2f5dc6ace81005d7d38ef666789e916a57
2021-10-27T17:25:20Z Available coins count 5 BestHeader: 1413736 05b471d200fc1a2e101292cea31def2f5dc6ace81005d7d38ef666789e916a57
2021-10-27T17:25:36Z Available coins count 5 BestHeader: 1413736 05b471d200fc1a2e101292cea31def2f5dc6ace81005d7d38ef666789e916a57
2021-10-27T17:25:52Z Available coins count 5 BestHeader: 1413736 05b471d200fc1a2e101292cea31def2f5dc6ace81005d7d38ef666789e916a57
2021-10-27T17:26:08Z +++ Block connected to chain: 1413737 BH: dbf7f3a4d4b98570b754228cb1aa349e787ce89312932ae5341f73f0fa91e69b CC: 0 (0)
2021-10-27T17:26:08Z Available coins count 5 BestHeader: 1413737 dbf7f3a4d4b98570b754228cb1aa349e787ce89312932ae5341f73f0fa91e69b
2021-10-27T17:26:11Z RIDB rollback to block height 1413736 success!
```

/var/log/syslog
```
Oct 27 17:26:11 pocket-01-node-vm kernel: [137835.137783] pocketcoin-http[21661]: segfault at 8 ip 000055ad992e8092 sp 00007fb2b2ff9050 error 4 in pocketcoind[55ad99078000+d3d000]
Oct 27 17:26:11 pocket-01-node-vm kernel: [137835.149870] Code: 55 49 89 d5 41 54 55 53 48 89 fb 48 83 ec 48 64 48 8b 04 25 28 00 00 00 48 89 44 24 38 31 c0 48 8b 06 c7 44 24 0c 00 00 00 00 <48> 8b 68 08 4c 8b 38 48 85 ed 74 13 48 83 3d b2 ae d0 00 00 0f 84
```

This _could_ be related to the "RIDB rollback" sometimes crashing?

If any other node operators could post the last few debug.log lines and also search your /var/log/syslog of segfaults, maybe we can gather enough information to correlate the issue an pinpoint the bug?

Thanks,

-DM

**Comment by tawmaz** [comment] 2021-10-29 20:05
I created a debug version with source symbols here for anyone who wants to assist in finding root cause for the segfault: https://github.com/tawmaz/pocketnet.core/releases/tag/v0.19.17dbg
Note this is a debug version only and will not fix any problems for your nodes. I am running it on two nodes and hopefully will have a repro soon.
I only tested in under ubuntu 20.04 LTS, found some missing dependencies on 18.04.  You will need to run 'ulimit -C unlimited' before starting pocketcoind to ensure the coredump is generated.  Where the core dump is generated depends on distribution, here is info for ubuntu: https://stackoverflow.com/questions/6152232/how-to-generate-core-dump-file-in-ubuntu

**Comment by tawmaz** [comment] 2021-10-29 20:10
@americanpatriotdave It is possible that the segfault is due to running out of memory.  In the case you posted it looks like the application correctly exited.  It is also possible for a memory allocation to fail and the program keeps running (because it does not perform the check to make sure is succeeded) causing a segfault.
On my production nodes I have been running 16 gig of ram with a 16 gig swap file.

**Comment by tapefive** [comment] 2021-10-31 12:27
I've been experiencing this too. Haven't checked logs, just says 'killed' in terminal. Which then requires a resync. My node only has 16GB RAM though..

**Comment by americanpatriotdave** [comment] 2021-10-31 14:20
32 GB of RAM is available to each of my nodes.  16G is used based on the "free" command running continuously

**Comment by tapefive** [comment] 2021-10-31 14:30
I've been experiencing more crashes too since upgrading to 19.17 

Not sure what's going on haven't checked the logs but just says 'killed' in the terminal when I check node to see if all ok. 

My node only has 16GB RAM and i'm not buying more for it so tempted to just stop running a node until a fix is implemented and Pocketnet Core doesn't require as much resource, as it's just a waste of electricity at this point.

**Comment by tapefive** [comment] 2021-10-31 14:31
I'll check the logs next time it's 'killed' and share in here.

**Comment by americanpatriotdave** [comment] 2021-11-02 20:25
Another silent death event.  Running 19.18.  Nothing in the debug log.  Log set to "sync" level.  nothing in syslog.  Seems like the same type of fail from 19.17.

**Comment by tawmaz** [comment] 2021-11-02 22:04
I added debug info from the segfault which I believe is causing this issue here: https://github.com/pocketnetteam/pocketnet.core/issues/80
I think what is happening is the node is getting a http gethierarchicalposts request right before/during/after a RIBD rollback.  Likely some of the expected data is no longer there causing a segfault in reindexer.

**Comment by andyoknen** [comment] 2021-11-03 08:11
@tawmaz I think this may be true, since we did not introduce mutexes to RPC requests and internal logic of working with the chain for performance reasons.

**Comment by andyoknen** [comment] 2021-11-03 08:12
I will close this issue - I propose to continue the discussion and the results in #80

**Closed by andyoknen** 2021-11-03 08:12 UTC
